/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const PriceRange = IDL.Variant({
  'premium' : IDL.Null,
  'budget' : IDL.Null,
  'standard' : IDL.Null,
});
export const CateringCategory = IDL.Variant({
  'festival' : IDL.Null,
  'wedding' : IDL.Null,
  'birthday' : IDL.Null,
  'corporate' : IDL.Null,
});
export const CateringService = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'priceRange' : PriceRange,
  'imageUrl' : IDL.Text,
  'category' : CateringCategory,
  'phone' : IDL.Text,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const MatrimonyProfile = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'education' : IDL.Text,
  'community' : IDL.Text,
  'profession' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'gender' : Gender,
  'contactEmail' : IDL.Text,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InquirySubject = IDL.Variant({
  'matrimony' : IDL.Null,
  'catering' : IDL.Null,
  'general' : IDL.Null,
});
export const ContactInquiry = IDL.Record({
  'subject' : InquirySubject,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCateringService' : IDL.Func([CateringService], [IDL.Nat], []),
  'addMatrimonyProfile' : IDL.Func([MatrimonyProfile], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCateringService' : IDL.Func([IDL.Nat], [], []),
  'deleteMatrimonyProfile' : IDL.Func([IDL.Nat], [], []),
  'filterMatrimonyProfiles' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(Gender)],
      [IDL.Vec(MatrimonyProfile)],
      ['query'],
    ),
  'getAllActiveCateringServices' : IDL.Func(
      [],
      [IDL.Vec(CateringService)],
      ['query'],
    ),
  'getAllActiveMatrimonyProfiles' : IDL.Func(
      [],
      [IDL.Vec(MatrimonyProfile)],
      ['query'],
    ),
  'getAllContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactInquiry' : IDL.Func([ContactInquiry], [IDL.Nat], []),
  'updateCateringService' : IDL.Func([IDL.Nat, CateringService], [], []),
  'updateMatrimonyProfile' : IDL.Func([IDL.Nat, MatrimonyProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const PriceRange = IDL.Variant({
    'premium' : IDL.Null,
    'budget' : IDL.Null,
    'standard' : IDL.Null,
  });
  const CateringCategory = IDL.Variant({
    'festival' : IDL.Null,
    'wedding' : IDL.Null,
    'birthday' : IDL.Null,
    'corporate' : IDL.Null,
  });
  const CateringService = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'priceRange' : PriceRange,
    'imageUrl' : IDL.Text,
    'category' : CateringCategory,
    'phone' : IDL.Text,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const MatrimonyProfile = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'education' : IDL.Text,
    'community' : IDL.Text,
    'profession' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'gender' : Gender,
    'contactEmail' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InquirySubject = IDL.Variant({
    'matrimony' : IDL.Null,
    'catering' : IDL.Null,
    'general' : IDL.Null,
  });
  const ContactInquiry = IDL.Record({
    'subject' : InquirySubject,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCateringService' : IDL.Func([CateringService], [IDL.Nat], []),
    'addMatrimonyProfile' : IDL.Func([MatrimonyProfile], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCateringService' : IDL.Func([IDL.Nat], [], []),
    'deleteMatrimonyProfile' : IDL.Func([IDL.Nat], [], []),
    'filterMatrimonyProfiles' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(Gender)],
        [IDL.Vec(MatrimonyProfile)],
        ['query'],
      ),
    'getAllActiveCateringServices' : IDL.Func(
        [],
        [IDL.Vec(CateringService)],
        ['query'],
      ),
    'getAllActiveMatrimonyProfiles' : IDL.Func(
        [],
        [IDL.Vec(MatrimonyProfile)],
        ['query'],
      ),
    'getAllContactInquiries' : IDL.Func(
        [],
        [IDL.Vec(ContactInquiry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactInquiry' : IDL.Func([ContactInquiry], [IDL.Nat], []),
    'updateCateringService' : IDL.Func([IDL.Nat, CateringService], [], []),
    'updateMatrimonyProfile' : IDL.Func([IDL.Nat, MatrimonyProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };