/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CateringCategory = { 'festival' : null } |
  { 'wedding' : null } |
  { 'birthday' : null } |
  { 'corporate' : null };
export interface CateringService {
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'priceRange' : PriceRange,
  'imageUrl' : string,
  'category' : CateringCategory,
  'phone' : string,
}
export interface ContactInquiry {
  'subject' : InquirySubject,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type InquirySubject = { 'matrimony' : null } |
  { 'catering' : null } |
  { 'general' : null };
export interface MatrimonyProfile {
  'age' : bigint,
  'bio' : string,
  'name' : string,
  'createdAt' : Time,
  'education' : string,
  'community' : string,
  'profession' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'gender' : Gender,
  'contactEmail' : string,
  'location' : string,
}
export type PriceRange = { 'premium' : null } |
  { 'budget' : null } |
  { 'standard' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCateringService' : ActorMethod<[CateringService], bigint>,
  'addMatrimonyProfile' : ActorMethod<[MatrimonyProfile], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCateringService' : ActorMethod<[bigint], undefined>,
  'deleteMatrimonyProfile' : ActorMethod<[bigint], undefined>,
  'filterMatrimonyProfiles' : ActorMethod<
    [[] | [string], [] | [string], [] | [Gender]],
    Array<MatrimonyProfile>
  >,
  'getAllActiveCateringServices' : ActorMethod<[], Array<CateringService>>,
  'getAllActiveMatrimonyProfiles' : ActorMethod<[], Array<MatrimonyProfile>>,
  'getAllContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactInquiry' : ActorMethod<[ContactInquiry], bigint>,
  'updateCateringService' : ActorMethod<[bigint, CateringService], undefined>,
  'updateMatrimonyProfile' : ActorMethod<[bigint, MatrimonyProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];