/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface MatrimonyProfile {
    age: bigint;
    bio: string;
    name: string;
    createdAt: Time;
    education: string;
    community: string;
    profession: string;
    isActive: boolean;
    imageUrl: string;
    gender: Gender;
    contactEmail: string;
    location: string;
}
export interface ContactInquiry {
    subject: InquirySubject;
    name: string;
    createdAt: Time;
    email: string;
    message: string;
    phone: string;
}
export interface UserProfile {
    name: string;
}
export interface CateringService {
    name: string;
    createdAt: Time;
    description: string;
    isActive: boolean;
    priceRange: PriceRange;
    imageUrl: string;
    category: CateringCategory;
    phone: string;
}
export enum CateringCategory {
    festival = "festival",
    wedding = "wedding",
    birthday = "birthday",
    corporate = "corporate"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum InquirySubject {
    matrimony = "matrimony",
    catering = "catering",
    general = "general"
}
export enum PriceRange {
    premium = "premium",
    budget = "budget",
    standard = "standard"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCateringService(service: CateringService): Promise<bigint>;
    addMatrimonyProfile(profile: MatrimonyProfile): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCateringService(id: bigint): Promise<void>;
    deleteMatrimonyProfile(id: bigint): Promise<void>;
    filterMatrimonyProfiles(community: string | null, location: string | null, gender: Gender | null): Promise<Array<MatrimonyProfile>>;
    getAllActiveCateringServices(): Promise<Array<CateringService>>;
    getAllActiveMatrimonyProfiles(): Promise<Array<MatrimonyProfile>>;
    getAllContactInquiries(): Promise<Array<ContactInquiry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitContactInquiry(inquiry: ContactInquiry): Promise<bigint>;
    updateCateringService(id: bigint, service: CateringService): Promise<void>;
    updateMatrimonyProfile(id: bigint, profile: MatrimonyProfile): Promise<void>;
}
import type { CateringCategory as _CateringCategory, CateringService as _CateringService, ContactInquiry as _ContactInquiry, Gender as _Gender, InquirySubject as _InquirySubject, MatrimonyProfile as _MatrimonyProfile, PriceRange as _PriceRange, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCateringService(arg0: CateringService): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCateringService(to_candid_CateringService_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCateringService(to_candid_CateringService_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMatrimonyProfile(arg0: MatrimonyProfile): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMatrimonyProfile(to_candid_MatrimonyProfile_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMatrimonyProfile(to_candid_MatrimonyProfile_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCateringService(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCateringService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCateringService(arg0);
            return result;
        }
    }
    async deleteMatrimonyProfile(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatrimonyProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatrimonyProfile(arg0);
            return result;
        }
    }
    async filterMatrimonyProfiles(arg0: string | null, arg1: string | null, arg2: Gender | null): Promise<Array<MatrimonyProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterMatrimonyProfiles(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterMatrimonyProfiles(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActiveCateringServices(): Promise<Array<CateringService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveCateringServices();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveCateringServices();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActiveMatrimonyProfiles(): Promise<Array<MatrimonyProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveMatrimonyProfiles();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveMatrimonyProfiles();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContactInquiries(): Promise<Array<ContactInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactInquiries();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactInquiries();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitContactInquiry(arg0: ContactInquiry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactInquiry(to_candid_ContactInquiry_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactInquiry(to_candid_ContactInquiry_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCateringService(arg0: bigint, arg1: CateringService): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCateringService(arg0, to_candid_CateringService_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCateringService(arg0, to_candid_CateringService_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMatrimonyProfile(arg0: bigint, arg1: MatrimonyProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatrimonyProfile(arg0, to_candid_MatrimonyProfile_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatrimonyProfile(arg0, to_candid_MatrimonyProfile_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CateringCategory_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CateringCategory): CateringCategory {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_CateringService_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CateringService): CateringService {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ContactInquiry_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactInquiry): ContactInquiry {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_InquirySubject_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquirySubject): InquirySubject {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_MatrimonyProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatrimonyProfile): MatrimonyProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_PriceRange_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceRange): PriceRange {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bio: string;
    name: string;
    createdAt: _Time;
    education: string;
    community: string;
    profession: string;
    isActive: boolean;
    imageUrl: string;
    gender: _Gender;
    contactEmail: string;
    location: string;
}): {
    age: bigint;
    bio: string;
    name: string;
    createdAt: Time;
    education: string;
    community: string;
    profession: string;
    isActive: boolean;
    imageUrl: string;
    gender: Gender;
    contactEmail: string;
    location: string;
} {
    return {
        age: value.age,
        bio: value.bio,
        name: value.name,
        createdAt: value.createdAt,
        education: value.education,
        community: value.community,
        profession: value.profession,
        isActive: value.isActive,
        imageUrl: value.imageUrl,
        gender: from_candid_Gender_n18(_uploadFile, _downloadFile, value.gender),
        contactEmail: value.contactEmail,
        location: value.location
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: _Time;
    description: string;
    isActive: boolean;
    priceRange: _PriceRange;
    imageUrl: string;
    category: _CateringCategory;
    phone: string;
}): {
    name: string;
    createdAt: Time;
    description: string;
    isActive: boolean;
    priceRange: PriceRange;
    imageUrl: string;
    category: CateringCategory;
    phone: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        priceRange: from_candid_PriceRange_n23(_uploadFile, _downloadFile, value.priceRange),
        imageUrl: value.imageUrl,
        category: from_candid_CateringCategory_n25(_uploadFile, _downloadFile, value.category),
        phone: value.phone
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: _InquirySubject;
    name: string;
    createdAt: _Time;
    email: string;
    message: string;
    phone: string;
}): {
    subject: InquirySubject;
    name: string;
    createdAt: Time;
    email: string;
    message: string;
    phone: string;
} {
    return {
        subject: from_candid_InquirySubject_n30(_uploadFile, _downloadFile, value.subject),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        message: value.message,
        phone: value.phone
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    budget: null;
} | {
    standard: null;
}): PriceRange {
    return "premium" in value ? PriceRange.premium : "budget" in value ? PriceRange.budget : "standard" in value ? PriceRange.standard : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    festival: null;
} | {
    wedding: null;
} | {
    birthday: null;
} | {
    corporate: null;
}): CateringCategory {
    return "festival" in value ? CateringCategory.festival : "wedding" in value ? CateringCategory.wedding : "birthday" in value ? CateringCategory.birthday : "corporate" in value ? CateringCategory.corporate : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matrimony: null;
} | {
    catering: null;
} | {
    general: null;
}): InquirySubject {
    return "matrimony" in value ? InquirySubject.matrimony : "catering" in value ? InquirySubject.catering : "general" in value ? InquirySubject.general : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatrimonyProfile>): Array<MatrimonyProfile> {
    return value.map((x)=>from_candid_MatrimonyProfile_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CateringService>): Array<CateringService> {
    return value.map((x)=>from_candid_CateringService_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactInquiry>): Array<ContactInquiry> {
    return value.map((x)=>from_candid_ContactInquiry_n28(_uploadFile, _downloadFile, x));
}
function to_candid_CateringCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CateringCategory): _CateringCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CateringService_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CateringService): _CateringService {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ContactInquiry_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactInquiry): _ContactInquiry {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_InquirySubject_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquirySubject): _InquirySubject {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_MatrimonyProfile_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatrimonyProfile): _MatrimonyProfile {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_PriceRange_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceRange): _PriceRange {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender | null): [] | [_Gender] {
    return value === null ? candid_none() : candid_some(to_candid_Gender_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: Time;
    description: string;
    isActive: boolean;
    priceRange: PriceRange;
    imageUrl: string;
    category: CateringCategory;
    phone: string;
}): {
    name: string;
    createdAt: _Time;
    description: string;
    isActive: boolean;
    priceRange: _PriceRange;
    imageUrl: string;
    category: _CateringCategory;
    phone: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        priceRange: to_candid_PriceRange_n3(_uploadFile, _downloadFile, value.priceRange),
        imageUrl: value.imageUrl,
        category: to_candid_CateringCategory_n5(_uploadFile, _downloadFile, value.category),
        phone: value.phone
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subject: InquirySubject;
    name: string;
    createdAt: Time;
    email: string;
    message: string;
    phone: string;
}): {
    subject: _InquirySubject;
    name: string;
    createdAt: _Time;
    email: string;
    message: string;
    phone: string;
} {
    return {
        subject: to_candid_InquirySubject_n37(_uploadFile, _downloadFile, value.subject),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        message: value.message,
        phone: value.phone
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bio: string;
    name: string;
    createdAt: Time;
    education: string;
    community: string;
    profession: string;
    isActive: boolean;
    imageUrl: string;
    gender: Gender;
    contactEmail: string;
    location: string;
}): {
    age: bigint;
    bio: string;
    name: string;
    createdAt: _Time;
    education: string;
    community: string;
    profession: string;
    isActive: boolean;
    imageUrl: string;
    gender: _Gender;
    contactEmail: string;
    location: string;
} {
    return {
        age: value.age,
        bio: value.bio,
        name: value.name,
        createdAt: value.createdAt,
        education: value.education,
        community: value.community,
        profession: value.profession,
        isActive: value.isActive,
        imageUrl: value.imageUrl,
        gender: to_candid_Gender_n9(_uploadFile, _downloadFile, value.gender),
        contactEmail: value.contactEmail,
        location: value.location
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquirySubject): {
    matrimony: null;
} | {
    catering: null;
} | {
    general: null;
} {
    return value == InquirySubject.matrimony ? {
        matrimony: null
    } : value == InquirySubject.catering ? {
        catering: null
    } : value == InquirySubject.general ? {
        general: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceRange): {
    premium: null;
} | {
    budget: null;
} | {
    standard: null;
} {
    return value == PriceRange.premium ? {
        premium: null
    } : value == PriceRange.budget ? {
        budget: null
    } : value == PriceRange.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CateringCategory): {
    festival: null;
} | {
    wedding: null;
} | {
    birthday: null;
} | {
    corporate: null;
} {
    return value == CateringCategory.festival ? {
        festival: null
    } : value == CateringCategory.wedding ? {
        wedding: null
    } : value == CateringCategory.birthday ? {
        birthday: null
    } : value == CateringCategory.corporate ? {
        corporate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
